version: "3.9"
services:
  laravel-mysql:
    container_name: laravel-mysql
    hostname: laravel-mysql
    image: mysql:8.0.30
    volumes:
      - laravel-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    networks:
      - laravel-network
  laravel:
    container_name: laravel
    privileged: true
    hostname: laravel
    build:
      args:
        user: LARAVEL
        uid: 1000
      context: ./laravel
      dockerfile: ../docker/Dockerfile
    volumes:
      - ./laravel:/var/www
      - ./docker/php-docker.ini:/usr/local/etc/php/conf.d/docker-php.ini
    networks:
      - laravel-network
  nginx:
    image: nginx:1.17-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge
volumes:
  laravel-db: